# Generated by Django 4.2.7 on 2023-12-08 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('country', models.CharField(choices=[('india', 'india'), ('china', 'china')], default='india', max_length=20)),
                ('state', models.CharField(choices=[('karnataka', 'karnataka'), ('haryana', 'haryana')], default='karnataka', max_length=20)),
                ('district', models.CharField(choices=[('xyz', 'xyz'), ('abc', 'abc')], default='udupi', max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=200)),
                ('housetype', models.CharField(choices=[('1bhk', '1bhk'), ('2bhk', '2bhk')], default='1bhk', max_length=50)),
                ('contact', models.IntegerField(default=1234567891)),
                ('desp', models.TextField(default='hello')),
                ('issold', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
